version: '3.8'

services:
  hashicups-frontend:
    image: hashicorpdemoapp/frontend:v1.0.9
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_PUBLIC_API_URL=http://hashicups-api:8081
    depends_on:
      - hashicups-api
    networks:
      - hashicups-network

  hashicups-api:
    image: hashicorpdemoapp/public-api:v0.0.7
    ports:
      - "8081:8081"
    depends_on:
      - hashicups-database
    environment:
      - PAYMENT_API_URI=http://hashicups-payments:8080
      - BIND_ADDRESS=:8081
      - PRODUCT_API_URI=http://hashicups-product:9090
      - CORS_ALLOWED_ORIGINS=http://localhost:3000  
    networks:
      - hashicups-network

  hashicups-database:
    image: hashicorpdemoapp/product-api-db:v0.0.22
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=hashicups
      - POSTGRES_PASSWORD=hashicups_pwd
    ports:
      - "5432:5432"
    volumes:
      - hashicups-db-data:/var/lib/postgresql/data
    networks:
      - hashicups-network

  hashicups-product:
    image: hashicorpdemoapp/product-api:v0.0.22
    ports:
      - "9090:9090"
    volumes:
      - ./conf.json:/conf.json
    depends_on:
      - hashicups-database
    networks:
      - hashicups-network

networks:
  hashicups-network:
    driver: bridge

volumes:
  hashicups-db-data:
